export const LOAD_QUESTIONS_SUCCESS = "LOAD_COURSES_SUCCESS";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const DELETE_QUESTION_OPTIMISTIC = "LOAD_COURSES_OPTIMISTIC";

export const LOAD_QUESTION_TYPES_SUCCESS = "LOAD_QUESTION_TYPES_SUCCESS";
