export const LOAD_QUESTIONS_SUCCESS = "LOAD_COURSES_SUCCESS";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const DELETE_QUESTION_OPTIMISTIC = "LOAD_COURSES_OPTIMISTIC";

export const LOAD_QUESTION_TYPES_SUCCESS = "LOAD_QUESTION_TYPES_SUCCESS";

export const LOAD_TESTS_SUCCESS = "LOAD_TESTS_SUCCESS";
export const CREATE_TEST_SUCCESS = "CREATE_TEST_SUCCESS";
export const UPDATE_TEST_SUCCESS = "UPDATE_TEST_SUCCESS";
export const DELETE_TEST_OPTIMISTIC = "DELETE_TEST_OPTIMISTIC";

export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_OPTIMISTIC = "DELETE_USER_OPTIMISTIC";
